services:
  app:
    container_name: fleet-ms-backend
    build:
      context: .
      dockerfile: DockerfileLocal
      target: php
      args:
        - APP_ENV=${APP_ENV:-development}
    environment:
      - CONTAINER_ROLE=app
      - APP_ENV=${APP_ENV:-development}
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
    ports:
      - "2002:8080"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - laravel
    restart: unless-stopped

  database:
    container_name: fleet-ms-backend-database
    image: postgres:latest
    ports:
      - "2003:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./documentation/be-docker/data/postgres-data:/var/lib/postgresql
    networks:
      - laravel
    healthcheck:
      test: [ "CMD-SHELL", "exit 0" ]
    restart: unless-stopped

  horizon:
    container_name: fleet-ms-backend-horizon
    build:
      context: .
      dockerfile: DockerfileLocal
      target: php
    environment:
      - CONTAINER_ROLE=horizon
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      - laravel

  scheduler:
    container_name: fleet-ms-backend-scheduler
    build:
      context: .
      dockerfile: DockerfileLocal
      target: php
    environment:
      - CONTAINER_ROLE=scheduler
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - app
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: fleet-ms-backend-redis
    command: redis-server --appendonly yes
    volumes:
      - ./documentation/be-docker/data/redis-data/data:/data
    networks:
      - laravel
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  mailpit:
    image: axllent/mailpit:latest
    container_name: fleet-ms-backend-mailpit
    ports:
      - "2004:8025"  # Web UI
#      - "2005:1025"  # SMTP
    networks:
      - laravel
    restart: unless-stopped

volumes:
  mysql-data:
  redis-data:

networks:
  laravel:
    driver: bridge
